import React from "react";
import { type Metadata } from "next";
import ClerkProviderWrapper from "@/app/components/ClerkProviderWrapper";
import "./globals.css";
import QueryClientProvider from "@/app/components/QueryClientProvider";
import HeaderNav from "@/app/components/HeaderNav";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <QueryClientProvider>
        <html lang="en">
          <body
            className={` antialiased`}
          >
            <React.Suspense fallback={null}>
              <HeaderNav />
            </React.Suspense>
            <React.Suspense fallback={null}>
              {children}
            </React.Suspense>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProviderWrapper>
  );
}
