import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import QueryClientProvider from "@/app/components/QueryClientProvider";
import HeaderNav from "@/app/components/HeaderNav";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryClientProvider>
        <html lang="en">
          <body
            className={` antialiased`}
          >
            <HeaderNav />
            {children}
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  );
}
